version: "3.9"
services:
  app:
    container_name: app
    image: app
    build: app
    restart: always
  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
